version: "3"

services:
  compiler-explorer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mordante/compiler-explorer:latest
    container_name: compiler-explorer
    ports:
      - 10240:10240
    volumes:
      - ./libcxx:/libcxx
    networks:
      - compiler-explorer
    restart: on-failure
    stop_grace_period: 1m

networks:
  compiler-explorer:
